version: "3.8"

services:
    basaran:
        image: hyperonym/basaran:0.12.0
        restart: always
        environment:
            MODEL: "bigscience/bloomz-560m"
            SERVER_MODEL_NAME: "bloomz-560m"
        ports:
            - "80:80"
